package meson

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/neprel/git-a2a/internal/adapter"
)

const (
	rootFile      = "meson.build"
	generatedFile = "deps/git-a2a/meson.build"
	includeLine   = "subdir('deps/git-a2a') # git-a2a"
	header        = "# Generated by git-a2a; do not edit.\n"
)

type Adapter struct{}

func (Adapter) Ecosystem() string { return "meson" }

func (Adapter) Detect(root string) (bool, adapter.Variant, error) {
	_, err := os.Stat(filepath.Join(root, rootFile))
	if os.IsNotExist(err) {
		return false, "", nil
	}
	return err == nil, "meson", err
}

func (a Adapter) Wire(_ context.Context, root string, dep adapter.Dependency, exp adapter.Export, locked adapter.Locked) (adapter.Change, error) {
	if dep.Vendor == nil || locked.Vendor == nil {
		return adapter.Change{}, adapter.NotWirable("Meson subproject integration requires an explicitly vendored dependency")
	}
	if err := validatePath(dep, exp, locked); err != nil {
		return adapter.Change{}, err
	}
	if ok, _, err := a.Detect(root); err != nil || !ok {
		return adapter.Change{}, err
	}
	generatedPath := filepath.Join(root, filepath.FromSlash(generatedFile))
	before, err := readGenerated(generatedPath)
	if err != nil {
		return adapter.Change{}, err
	}
	blocks, discarded := parseBlocks(before)
	blocks[dep.ID] = block(dep.ID)
	nextGenerated := renderBlocks(blocks)
	rootPath := filepath.Join(root, rootFile)
	rootBefore, err := os.ReadFile(rootPath)
	if err != nil {
		return adapter.Change{}, err
	}
	rootAfter := ensureLine(rootBefore, includeLine)
	changed := string(before) != string(nextGenerated) || string(rootBefore) != string(rootAfter)
	if !changed {
		return adapter.Change{File: generatedFile, Entry: dep.ID}, nil
	}
	if err = os.MkdirAll(filepath.Dir(generatedPath), 0o755); err == nil {
		err = os.WriteFile(generatedPath, nextGenerated, 0o644)
	}
	if err == nil {
		err = os.WriteFile(rootPath, rootAfter, 0o644)
	}
	warning := ""
	if discarded {
		warning = generatedFile + " contained foreign content; git-a2a regenerated the owned file and discarded it"
	}
	return adapter.Change{File: generatedFile, Entry: dep.ID, Changed: true, Warning: warning}, err
}

func (Adapter) Unwire(_ context.Context, root string, dep adapter.Dependency, _ adapter.Export) (adapter.Change, error) {
	generatedPath := filepath.Join(root, filepath.FromSlash(generatedFile))
	before, err := readGenerated(generatedPath)
	if err != nil {
		return adapter.Change{}, err
	}
	blocks, discarded := parseBlocks(before)
	_, hadBlock := blocks[dep.ID]
	delete(blocks, dep.ID)
	if len(blocks) == 0 {
		if err = os.Remove(generatedPath); err != nil && !os.IsNotExist(err) {
			return adapter.Change{}, err
		}
		rootPath := filepath.Join(root, rootFile)
		body, readErr := os.ReadFile(rootPath)
		if readErr != nil {
			return adapter.Change{}, readErr
		}
		err = os.WriteFile(rootPath, removeLine(body, includeLine), 0o644)
	} else {
		err = os.WriteFile(generatedPath, renderBlocks(blocks), 0o644)
	}
	return adapter.Change{File: generatedFile, Entry: dep.ID, Changed: hadBlock || discarded || len(before) > 0}, err
}

func (a Adapter) Refresh(ctx context.Context, root string, _ adapter.Dependency, _ adapter.Export, _ adapter.Locked) error {
	if err := adapter.RequireTool(ctx, a.Ecosystem(), "meson"); err != nil {
		return err
	}
	build, err := os.MkdirTemp("", "git-a2a-meson-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(build)
	if err = adapter.Command(ctx, root, "meson", "setup", build, root); err != nil {
		return err
	}
	return adapter.Command(ctx, root, "meson", "compile", "-C", build)
}

func (Adapter) Drift(_ context.Context, root string, dep adapter.Dependency, exp adapter.Export, locked adapter.Locked) ([]adapter.Finding, error) {
	if dep.Vendor == nil || locked.Vendor == nil {
		return []adapter.Finding{{File: generatedFile, Entry: dep.ID, Want: "vendored Meson integration", Got: "not vendored"}}, nil
	}
	if err := validatePath(dep, exp, locked); err != nil {
		return []adapter.Finding{{File: generatedFile, Entry: dep.ID, Want: filepath.ToSlash(filepath.Join("subprojects", dep.ID)), Got: sourcePath(exp, locked)}}, nil
	}
	body, err := readGenerated(filepath.Join(root, filepath.FromSlash(generatedFile)))
	if err != nil {
		return nil, err
	}
	blocks, discarded := parseBlocks(body)
	want := block(dep.ID)
	var findings []adapter.Finding
	if blocks[dep.ID] != want {
		findings = append(findings, adapter.Finding{File: generatedFile, Entry: dep.ID, Want: strings.TrimSpace(want), Got: strings.TrimSpace(blocks[dep.ID])})
	}
	if discarded {
		findings = append(findings, adapter.Finding{File: generatedFile, Entry: "owned file", Want: "only generated git-a2a content", Got: "foreign content"})
	}
	rootBody, readErr := os.ReadFile(filepath.Join(root, rootFile))
	if readErr != nil {
		return nil, readErr
	}
	if !hasLine(rootBody, includeLine) {
		findings = append(findings, adapter.Finding{File: rootFile, Entry: "git-a2a include", Want: includeLine, Got: ""})
	}
	return findings, nil
}

func validatePath(dep adapter.Dependency, exp adapter.Export, locked adapter.Locked) error {
	want := filepath.ToSlash(filepath.Join("subprojects", dep.ID))
	if got := sourcePath(exp, locked); got != want {
		return fmt.Errorf("Meson requires vendor.path %q with no dependency/export subpath (got %q); run git-a2a set %s --vendor %s --vendor-path %s", want, got, dep.ID, locked.Vendor.Mode, want)
	}
	return nil
}

func sourcePath(exp adapter.Export, locked adapter.Locked) string {
	parts := []string{locked.Vendor.Path}
	if locked.Vendor.Mode == "submodule" && locked.Path != "" && locked.Path != "." {
		parts = append(parts, locked.Path)
	}
	if exp.Path != "" && exp.Path != "." {
		parts = append(parts, exp.Path)
	}
	return filepath.ToSlash(filepath.Join(parts...))
}

func block(id string) string {
	return fmt.Sprintf("# git-a2a:begin %s\nsubproject('%s')\n# git-a2a:end %s\n", id, id, id)
}

var blockPattern = regexp.MustCompile(`(?ms)^# git-a2a:begin ([a-z0-9][a-z0-9._-]*)\n.*?^# git-a2a:end ([a-z0-9][a-z0-9._-]*)\n?`)

func readGenerated(path string) ([]byte, error) {
	body, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	return body, err
}

func parseBlocks(body []byte) (map[string]string, bool) {
	blocks := map[string]string{}
	if len(body) == 0 {
		return blocks, false
	}
	text := string(body)
	hasHeader := strings.HasPrefix(text, header)
	remainder := strings.TrimPrefix(text, header)
	for _, match := range blockPattern.FindAllStringSubmatch(text, -1) {
		if match[1] != match[2] {
			continue
		}
		blocks[match[1]] = match[0]
		remainder = strings.Replace(remainder, match[0], "", 1)
	}
	return blocks, !hasHeader || strings.TrimSpace(remainder) != ""
}

func renderBlocks(blocks map[string]string) []byte {
	ids := make([]string, 0, len(blocks))
	for id := range blocks {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	var out strings.Builder
	out.WriteString(header)
	for _, id := range ids {
		out.WriteString(blocks[id])
	}
	return []byte(out.String())
}

func hasLine(body []byte, line string) bool {
	for _, current := range strings.Split(strings.ReplaceAll(string(body), "\r\n", "\n"), "\n") {
		if current == line {
			return true
		}
	}
	return false
}

func ensureLine(body []byte, line string) []byte {
	if hasLine(body, line) {
		return body
	}
	text := string(body)
	if text != "" && !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	return []byte(text + line + "\n")
}

func removeLine(body []byte, line string) []byte {
	lines := strings.SplitAfter(string(body), "\n")
	out := lines[:0]
	for _, current := range lines {
		if strings.TrimSuffix(strings.TrimSuffix(current, "\n"), "\r") != line {
			out = append(out, current)
		}
	}
	return []byte(strings.Join(out, ""))
}
