package render

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/neprel/git-a2a/internal/cache"
	lockfile "github.com/neprel/git-a2a/internal/lock"
	"github.com/neprel/git-a2a/internal/manifest"
	"github.com/neprel/git-a2a/internal/routing"
)

const Begin = "<!-- git-a2a:begin -->"
const End = "<!-- git-a2a:end -->"

const (
	descriptionLimit = 600
	noteLimit        = 300
	fieldLimit       = 300
)

func Build(root string, own *manifest.Manifest, l *manifest.Lock, brief bool) (string, error) {
	var b strings.Builder
	b.WriteString(Begin + "\n## git-a2a module roster\n\n### This module: `" + own.Module.ID + "`\n\n")
	if own.Module.Description != "" {
		b.WriteString(own.Module.Description + "\n\n")
	}
	for _, a := range own.Agents {
		scope := a.Scope
		if len(scope) == 0 {
			scope = []string{"**"}
		}
		fmt.Fprintf(&b, "- `%s` (%s), scope: `%s`\n", a.Name, a.Role, strings.Join(scope, "`, `"))
	}
	writeConsumers(&b, own.Policy, false, "", "")
	ids := make([]string, 0, len(l.Dependencies))
	for id := range l.Dependencies {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		entry := l.Dependencies[id]
		dep, err := manifest.Load(filepath.Join(cache.Dir(root, id), "a2amodule.yml"))
		if err != nil {
			return "", fmt.Errorf("%s: %w", id, err)
		}
		fmt.Fprintf(&b, "\n### Dependency: `%s`\n\n", id)
		origin := fmt.Sprintf("from %s @%s", id, short(entry.Commit))
		if dep.Module.Description != "" {
			fmt.Fprintf(&b, "> Description (%s): %s\n>\n", origin, safe(dep.Module.Description, descriptionLimit))
		}
		if dep.Module.Surface != "" {
			fmt.Fprintf(&b, "> Published surface (%s): `.git-a2a/cache/%s/surface/` (available after `git-a2a show %s --surface`).\n>\n", origin, id, id)
		}
		if entry.Vendor != nil {
			fmt.Fprintf(&b, "> Vendored at `%s` (%s).", safe(entry.Vendor.Path, fieldLimit), safe(entry.Vendor.Mode, fieldLimit))
			if entry.Vendor.Mode == "submodule" {
				b.WriteString(" Clone with `--recurse-submodules`; repair an existing clone with `git submodule update --init` or `git-a2a wire`.")
			}
			b.WriteString("\n>\n")
		}
		writeConsumers(&b, dep.Policy, true, origin, id)
		b.WriteString("\n| Intent | Agent (role) | Declared contact |\n| --- | --- | --- |\n")
		for _, intent := range intents(dep) {
			matches, _ := routing.Resolve(dep, intent, "")
			if len(matches) == 0 {
				fmt.Fprintf(&b, "| %s | — | none declared |\n", safe(intent, fieldLimit))
				continue
			}
			contacts := matches[0].Contacts
			if brief && len(contacts) > 1 {
				contacts = contacts[:1]
			}
			for _, contact := range contacts {
				text := routing.ContactText(contact)
				if contact.Note != "" {
					text += "; note: " + sanitize(contact.Note, noteLimit)
				}
				fmt.Fprintf(&b, "| %s | %s (%s) | %s |\n", safe(intent, fieldLimit), safe(matches[0].Agent.Name, fieldLimit), safe(matches[0].Agent.Role, fieldLimit), safe(text, fieldLimit))
			}
		}
	}
	b.WriteString("\nGenerated by git-a2a from `a2amodule.yml` and `a2amodule.lock`; edits inside this block are overwritten. Use `git-a2a who <id> --intent <intent>` for the full contact list.\nRun `git-a2a usage` to learn the tool.\n" + End + "\n")
	return b.String(), nil
}

func writeConsumers(b *strings.Builder, p *manifest.Policy, quoted bool, origin, id string) {
	may := []string{"read-surface", "ask"}
	mayNot := []string{"commit"}
	notes := ""
	if p != nil {
		if p.Consumers != nil {
			if p.Consumers.May != nil {
				may = p.Consumers.May
			}
			if p.Consumers.MayNot != nil {
				mayNot = p.Consumers.MayNot
			}
		}
		notes = p.Notes
	}
	prefix := ""
	if quoted {
		prefix = "> "
		fmt.Fprintf(b, "> Consumer policy (%s):\n", origin)
	}
	mayText := strings.Join(may, "`, `")
	mayNotText := strings.Join(mayNot, "`, `")
	if quoted {
		mayText = safe(mayText, fieldLimit)
		mayNotText = safe(mayNotText, fieldLimit)
	}
	fmt.Fprintf(b, "%s- may: `%s`\n%s- may-not: `%s`\n", prefix, mayText, prefix, mayNotText)
	if notes != "" {
		if quoted {
			fmt.Fprintf(b, "> - notes: %s\n", safe(notes, noteLimit))
		} else {
			fmt.Fprintf(b, "- notes: %s\n", notes)
		}
	}
	_ = id
}

func intents(m *manifest.Manifest) []string {
	core := []string{"question", "change", "bug", "review", "incident"}
	seen := map[string]bool{}
	var extra []string
	for _, v := range core {
		seen[v] = true
	}
	if m.Policy != nil {
		for v := range m.Policy.Intents {
			if !seen[v] {
				seen[v] = true
				extra = append(extra, v)
			}
		}
	}
	for _, a := range m.Agents {
		for _, c := range a.Contacts {
			for _, v := range c.Intents {
				if v != "*" && !seen[v] {
					seen[v] = true
					extra = append(extra, v)
				}
			}
		}
	}
	sort.Strings(extra)
	return append(core, extra...)
}

func sanitize(s string, limit int) string {
	// Remove delimiter tokens themselves. Removing complete comments in one pass is
	// insufficient: nested-looking input can reveal a managed-block delimiter.
	s = strings.ReplaceAll(s, "<!--", "")
	s = strings.ReplaceAll(s, "-->", "")
	s = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) {
			return ' '
		}
		return r
	}, s)
	s = strings.Join(strings.Fields(s), " ")
	r := []rune(s)
	if len(r) > limit {
		marker := []rune("…[truncated]")
		if limit <= len(marker) {
			return string(marker[:limit])
		}
		return string(r[:limit-len(marker)]) + string(marker)
	}
	return s
}
func safe(s string, limit int) string { return escape(sanitize(s, limit)) }

// SanitizeMachineText applies the dependency-text boundary without Markdown escaping.
func SanitizeMachineText(s string, description bool) string {
	limit := fieldLimit
	if description {
		limit = descriptionLimit
	}
	return sanitize(s, limit)
}
func escape(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
func short(s string) string {
	if len(s) > 12 {
		return s[:12]
	}
	return s
}

func Apply(path, block string, check bool) (bool, error) {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	next, err := replace(string(existing), block)
	if err != nil {
		return false, err
	}
	if string(existing) == next {
		return false, nil
	}
	if check {
		return true, nil
	}
	return true, lockfile.Atomic(path, []byte(next), 0o644)
}
func Current(path, block string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	next, err := replace(string(b), block)
	return err == nil && next == string(b)
}

// HasManagedBlock reports whether a file has any git-a2a delimiter. A partial
// block counts as present so status can report it as stale instead of absent.
func HasManagedBlock(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(b), Begin) || strings.Contains(string(b), End)
}
func replace(existing, block string) (string, error) {
	if strings.Count(existing, End) > 1 {
		return "", fmt.Errorf("managed block has more than one end delimiter")
	}
	start := strings.Index(existing, Begin)
	end := strings.Index(existing, End)
	if (start < 0) != (end < 0) {
		return "", fmt.Errorf("managed block has only one delimiter")
	}
	if start >= 0 {
		end += len(End)
		if end < len(existing) && existing[end] == '\n' {
			end++
		}
		return existing[:start] + block + existing[end:], nil
	}
	if existing == "" {
		return block, nil
	}
	if !strings.HasSuffix(existing, "\n") {
		existing += "\n"
	}
	return existing + "\n" + block, nil
}
