// Generated by git-a2a; do not edit.
// git-a2a:begin acme-lib
includeBuild("deps/acme-lib/modules/lib/jvm") {
  dependencySubstitution {
    substitute(module("com.acme:lib-utils")).using(project(":"))
  }
}
// git-a2a:end acme-lib
