package cmake

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/neprel/git-a2a/internal/adapter"
)

const (
	rootFile      = "CMakeLists.txt"
	generatedFile = "deps/git-a2a.cmake"
	includeLine   = `include("deps/git-a2a.cmake") # git-a2a`
	header        = "# Generated by git-a2a; do not edit.\n"
)

type Adapter struct{}

func (Adapter) Ecosystem() string { return "cmake" }

func (Adapter) Detect(root string) (bool, adapter.Variant, error) {
	_, err := os.Stat(filepath.Join(root, rootFile))
	if os.IsNotExist(err) {
		return false, "", nil
	}
	return err == nil, "cmake", err
}

func (a Adapter) wire(_ context.Context, root string, dep adapter.Dependency, exp adapter.Export, _ adapter.Locked) (adapter.Change, error) {
	if exp.Path == "" || exp.Path == "." {
		return adapter.Change{}, adapter.NotWirable("cmake requires a materialized source checkout path")
	}
	if ok, _, err := a.Detect(root); err != nil || !ok {
		return adapter.Change{}, err
	}
	generatedPath := filepath.Join(root, filepath.FromSlash(generatedFile))
	before, err := readGenerated(generatedPath)
	if err != nil {
		return adapter.Change{}, err
	}
	blocks, discarded := parseBlocks(before)
	blocks[dep.Name] = block(dep.Name, sourcePath(exp))
	nextGenerated := renderBlocks(blocks)
	rootPath := filepath.Join(root, rootFile)
	rootBefore, err := os.ReadFile(rootPath)
	if err != nil {
		return adapter.Change{}, err
	}
	rootAfter := ensureLine(rootBefore, includeLine)
	changed := string(before) != string(nextGenerated) || string(rootBefore) != string(rootAfter)
	if !changed {
		return adapter.Change{File: generatedFile, Entry: dep.Name}, nil
	}
	if err = os.MkdirAll(filepath.Dir(generatedPath), 0o755); err == nil {
		err = os.WriteFile(generatedPath, nextGenerated, 0o644)
	}
	if err == nil {
		err = os.WriteFile(rootPath, rootAfter, 0o644)
	}
	warning := ""
	if discarded {
		warning = generatedFile + " contained foreign content; git-a2a regenerated the owned file and discarded it"
	}
	return adapter.Change{File: generatedFile, Entry: dep.Name, Changed: true, Warning: warning}, err
}

func (Adapter) unwire(_ context.Context, root string, dep adapter.Dependency, _ adapter.Export) (adapter.Change, error) {
	generatedPath := filepath.Join(root, filepath.FromSlash(generatedFile))
	before, err := readGenerated(generatedPath)
	if err != nil {
		return adapter.Change{}, err
	}
	blocks, discarded := parseBlocks(before)
	_, hadBlock := blocks[dep.Name]
	delete(blocks, dep.Name)
	if len(blocks) == 0 {
		if err = os.Remove(generatedPath); err != nil && !os.IsNotExist(err) {
			return adapter.Change{}, err
		}
		rootPath := filepath.Join(root, rootFile)
		body, readErr := os.ReadFile(rootPath)
		if readErr != nil {
			return adapter.Change{}, readErr
		}
		err = os.WriteFile(rootPath, removeLine(body, includeLine), 0o644)
	} else {
		err = os.WriteFile(generatedPath, renderBlocks(blocks), 0o644)
	}
	changed := hadBlock || discarded || len(before) > 0
	return adapter.Change{File: generatedFile, Entry: dep.Name, Changed: changed}, err
}

func (Adapter) resolve(ctx context.Context, root string) error {
	build := filepath.Join(root, ".git-a2a", "build", "cmake")
	if err := os.MkdirAll(filepath.Dir(build), 0o755); err != nil {
		return err
	}
	return adapter.Command(ctx, root, "cmake", "-S", root, "-B", build)
}

func (Adapter) inspectDeclaration(_ context.Context, root string, dep adapter.Dependency, exp adapter.Export, _ adapter.Locked) ([]adapter.Finding, error) {
	if exp.Path == "" || exp.Path == "." {
		return []adapter.Finding{{File: generatedFile, Entry: dep.Name, Want: "materialized source checkout path", Got: exp.Path}}, nil
	}
	body, err := readGenerated(filepath.Join(root, filepath.FromSlash(generatedFile)))
	if err != nil {
		return nil, err
	}
	blocks, discarded := parseBlocks(body)
	want := block(dep.Name, sourcePath(exp))
	var findings []adapter.Finding
	if blocks[dep.Name] != want {
		findings = append(findings, adapter.Finding{File: generatedFile, Entry: dep.Name, Want: strings.TrimSpace(want), Got: strings.TrimSpace(blocks[dep.Name]), Repairable: true})
	}
	if discarded {
		findings = append(findings, adapter.Finding{File: generatedFile, Entry: "owned file", Want: "only generated git-a2a content", Got: "foreign content"})
	}
	rootBody, readErr := os.ReadFile(filepath.Join(root, rootFile))
	if readErr != nil {
		return nil, readErr
	}
	if !hasLine(rootBody, includeLine) {
		findings = append(findings, adapter.Finding{File: rootFile, Entry: "git-a2a include", Want: includeLine, Got: "", Repairable: true})
	}
	return findings, nil
}

func sourcePath(exp adapter.Export) string {
	return filepath.ToSlash(filepath.Clean(exp.Path))
}

func block(id, path string) string {
	return fmt.Sprintf("# git-a2a:begin %s\nadd_subdirectory(\"%s\")\n# git-a2a:end %s\n", id, path, id)
}

var blockPattern = regexp.MustCompile(`(?ms)^# git-a2a:begin ([a-z0-9][a-z0-9._-]*)\n.*?^# git-a2a:end ([a-z0-9][a-z0-9._-]*)\n?`)

func readGenerated(path string) ([]byte, error) {
	body, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return body, nil
}

func parseBlocks(body []byte) (map[string]string, bool) {
	blocks := map[string]string{}
	if len(body) == 0 {
		return blocks, false
	}
	text := string(body)
	hasHeader := strings.HasPrefix(text, header)
	remainder := text
	if hasHeader {
		remainder = strings.TrimPrefix(remainder, header)
	}
	for _, match := range blockPattern.FindAllStringSubmatch(string(body), -1) {
		if match[1] != match[2] {
			continue
		}
		blocks[match[1]] = match[0]
		remainder = strings.Replace(remainder, match[0], "", 1)
	}
	discarded := !hasHeader || strings.TrimSpace(remainder) != ""
	return blocks, discarded
}

func renderBlocks(blocks map[string]string) []byte {
	ids := make([]string, 0, len(blocks))
	for id := range blocks {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	var out strings.Builder
	out.WriteString(header)
	for _, id := range ids {
		out.WriteString(blocks[id])
	}
	return []byte(out.String())
}

func hasLine(body []byte, line string) bool {
	for _, current := range strings.Split(strings.ReplaceAll(string(body), "\r\n", "\n"), "\n") {
		if current == line {
			return true
		}
	}
	return false
}

func ensureLine(body []byte, line string) []byte {
	if hasLine(body, line) {
		return body
	}
	text := string(body)
	if text != "" && !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	return []byte(text + line + "\n")
}

func removeLine(body []byte, line string) []byte {
	lines := strings.SplitAfter(string(body), "\n")
	out := lines[:0]
	for _, current := range lines {
		if strings.TrimSuffix(strings.TrimSuffix(current, "\n"), "\r") != line {
			out = append(out, current)
		}
	}
	return []byte(strings.Join(out, ""))
}
