package gradle

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/neprel/git-a2a/internal/adapter"
)

const header = "// Generated by git-a2a; do not edit.\n"

type Adapter struct{}

func (Adapter) Ecosystem() string { return "maven" }

func (Adapter) Detect(root string) (bool, adapter.Variant, error) {
	if _, err := os.Stat(filepath.Join(root, "settings.gradle.kts")); err == nil {
		return true, "gradle-kts", nil
	} else if !os.IsNotExist(err) {
		return false, "", err
	}
	if _, err := os.Stat(filepath.Join(root, "settings.gradle")); err == nil {
		return true, "gradle-groovy", nil
	} else if !os.IsNotExist(err) {
		return false, "", err
	}
	return false, "", nil
}

func (a Adapter) Wire(_ context.Context, root string, dep adapter.Dependency, exp adapter.Export, locked adapter.Locked) (adapter.Change, error) {
	if dep.Vendor == nil || locked.Vendor == nil {
		return adapter.Change{}, adapter.NotWirable("Gradle composite integration requires an explicitly vendored dependency")
	}
	ok, variant, err := a.Detect(root)
	if err != nil || !ok {
		return adapter.Change{}, err
	}
	generated, settings, line := files(variant)
	generatedPath := filepath.Join(root, filepath.FromSlash(generated))
	before, err := readGenerated(generatedPath)
	if err != nil {
		return adapter.Change{}, err
	}
	blocks, discarded := parseBlocks(before)
	blocks[dep.ID] = block(dep.ID, sourcePath(dep, exp, locked), exp.Name, variant)
	next := renderBlocks(blocks)
	settingsPath := filepath.Join(root, settings)
	settingsBefore, err := os.ReadFile(settingsPath)
	if err != nil {
		return adapter.Change{}, err
	}
	settingsAfter := ensureLine(settingsBefore, line)
	changed := !stringEqual(before, next) || !stringEqual(settingsBefore, settingsAfter)
	if !changed {
		return adapter.Change{File: generated, Entry: dep.ID}, nil
	}
	if err = os.MkdirAll(filepath.Dir(generatedPath), 0o755); err == nil {
		err = os.WriteFile(generatedPath, next, 0o644)
	}
	if err == nil {
		err = os.WriteFile(settingsPath, settingsAfter, 0o644)
	}
	warning := ""
	if discarded {
		warning = generated + " contained foreign content; git-a2a regenerated the owned file and discarded it"
	}
	return adapter.Change{File: generated, Entry: dep.ID, Changed: true, Warning: warning}, err
}

func (a Adapter) Unwire(_ context.Context, root string, dep adapter.Dependency, _ adapter.Export) (adapter.Change, error) {
	ok, variant, err := a.Detect(root)
	if err != nil || !ok {
		return adapter.Change{}, err
	}
	generated, settings, line := files(variant)
	generatedPath := filepath.Join(root, filepath.FromSlash(generated))
	before, err := readGenerated(generatedPath)
	if err != nil {
		return adapter.Change{}, err
	}
	blocks, discarded := parseBlocks(before)
	_, hadBlock := blocks[dep.ID]
	delete(blocks, dep.ID)
	if len(blocks) == 0 {
		if err = os.Remove(generatedPath); err != nil && !os.IsNotExist(err) {
			return adapter.Change{}, err
		}
		settingsPath := filepath.Join(root, settings)
		body, readErr := os.ReadFile(settingsPath)
		if readErr != nil {
			return adapter.Change{}, readErr
		}
		err = os.WriteFile(settingsPath, removeLine(body, line), 0o644)
	} else {
		err = os.WriteFile(generatedPath, renderBlocks(blocks), 0o644)
	}
	changed := hadBlock || discarded || len(before) > 0
	return adapter.Change{File: generated, Entry: dep.ID, Changed: changed}, err
}

func (a Adapter) Refresh(ctx context.Context, root string, _ adapter.Dependency, _ adapter.Export, _ adapter.Locked) error {
	ok, variant, err := a.Detect(root)
	if err != nil || !ok {
		return err
	}
	if err = adapter.RequireTool(ctx, a.Ecosystem(), variant); err != nil {
		return err
	}
	return adapter.Command(ctx, root, "gradle", "--no-daemon", "build")
}

func (a Adapter) Drift(_ context.Context, root string, dep adapter.Dependency, exp adapter.Export, locked adapter.Locked) ([]adapter.Finding, error) {
	ok, variant, err := a.Detect(root)
	if err != nil || !ok {
		return nil, err
	}
	generated, settings, line := files(variant)
	body, err := readGenerated(filepath.Join(root, filepath.FromSlash(generated)))
	if err != nil {
		return nil, err
	}
	blocks, discarded := parseBlocks(body)
	want := block(dep.ID, sourcePath(dep, exp, locked), exp.Name, variant)
	var findings []adapter.Finding
	if blocks[dep.ID] != want {
		findings = append(findings, adapter.Finding{File: generated, Entry: dep.ID, Want: strings.TrimSpace(want), Got: strings.TrimSpace(blocks[dep.ID])})
	}
	if discarded {
		findings = append(findings, adapter.Finding{File: generated, Entry: "owned file", Want: "only generated git-a2a content", Got: "foreign content"})
	}
	settingsBody, readErr := os.ReadFile(filepath.Join(root, settings))
	if readErr != nil {
		return nil, readErr
	}
	if !hasLine(settingsBody, line) {
		findings = append(findings, adapter.Finding{File: settings, Entry: "git-a2a apply", Want: line, Got: ""})
	}
	return findings, nil
}

func files(variant adapter.Variant) (generated, settings, line string) {
	if variant == "gradle-groovy" {
		return "deps/git-a2a.settings.gradle", "settings.gradle", `apply from: "deps/git-a2a.settings.gradle" // git-a2a`
	}
	return "deps/git-a2a.settings.gradle.kts", "settings.gradle.kts", `apply(from = "deps/git-a2a.settings.gradle.kts") // git-a2a`
}

func sourcePath(dep adapter.Dependency, exp adapter.Export, locked adapter.Locked) string {
	parts := []string{locked.Vendor.Path}
	if locked.Vendor.Mode == "submodule" && locked.Path != "" && locked.Path != "." {
		parts = append(parts, locked.Path)
	}
	if exp.Path != "" && exp.Path != "." {
		parts = append(parts, exp.Path)
	}
	return filepath.ToSlash(filepath.Join(parts...))
}

func block(id, path, coordinate string, variant adapter.Variant) string {
	if variant == "gradle-groovy" {
		return fmt.Sprintf("// git-a2a:begin %s\nincludeBuild(\"%s\") {\n  dependencySubstitution {\n    substitute module(\"%s\") using project(\":\")\n  }\n}\n// git-a2a:end %s\n", id, path, coordinate, id)
	}
	return fmt.Sprintf("// git-a2a:begin %s\nincludeBuild(\"%s\") {\n  dependencySubstitution {\n    substitute(module(\"%s\")).using(project(\":\"))\n  }\n}\n// git-a2a:end %s\n", id, path, coordinate, id)
}

var blockPattern = regexp.MustCompile(`(?ms)^// git-a2a:begin ([a-z0-9][a-z0-9._-]*)\n.*?^// git-a2a:end ([a-z0-9][a-z0-9._-]*)\n?`)

func readGenerated(path string) ([]byte, error) {
	body, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return body, nil
}

func parseBlocks(body []byte) (map[string]string, bool) {
	blocks := map[string]string{}
	if len(body) == 0 {
		return blocks, false
	}
	text := string(body)
	hasHeader := strings.HasPrefix(text, header)
	remainder := text
	if hasHeader {
		remainder = strings.TrimPrefix(remainder, header)
	}
	for _, match := range blockPattern.FindAllStringSubmatch(string(body), -1) {
		if match[1] != match[2] {
			continue
		}
		blocks[match[1]] = match[0]
		remainder = strings.Replace(remainder, match[0], "", 1)
	}
	return blocks, !hasHeader || strings.TrimSpace(remainder) != ""
}

func renderBlocks(blocks map[string]string) []byte {
	ids := make([]string, 0, len(blocks))
	for id := range blocks {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	var out strings.Builder
	out.WriteString(header)
	for _, id := range ids {
		out.WriteString(blocks[id])
	}
	return []byte(out.String())
}

func stringEqual(left, right []byte) bool { return string(left) == string(right) }

func hasLine(body []byte, line string) bool {
	for _, current := range strings.Split(strings.ReplaceAll(string(body), "\r\n", "\n"), "\n") {
		if current == line {
			return true
		}
	}
	return false
}

func ensureLine(body []byte, line string) []byte {
	if hasLine(body, line) {
		return body
	}
	text := string(body)
	if text != "" && !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	return []byte(text + line + "\n")
}

func removeLine(body []byte, line string) []byte {
	lines := strings.SplitAfter(string(body), "\n")
	out := lines[:0]
	for _, current := range lines {
		if strings.TrimSuffix(strings.TrimSuffix(current, "\n"), "\r") != line {
			out = append(out, current)
		}
	}
	return []byte(strings.Join(out, ""))
}
